### ISSUE TITLE
start implementing TOR network integration into wallet

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1575]
We are already about 80% through on Android platform with this, see coimpleted/progressing issues below for reference:

- https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1805
- https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1813
- https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1862
- https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1823

@ant013 Perhaps, you should arrange a talk with @rafaelekol and @nk-the-crazy before getting on the task. Also invite @ealymbaev to the talk as we need his consent before applying anything.

- [ ] create Networking Kit for Swift
- [ ] break the task into multiple issues if needed
- [ ] implement TOR support into app (refer to @TalgatNurdinov for UI/UX elements, it's ready)

**Comment by esengulov** [comment]
https://github.com/iCepa/Tor.framework/issues/54#issuecomment-614059040

**Comment by gmale** [comment]
I'm just curious, what approach do you think will work on the iOS side, particularly for gRPC? Are you thinking to create custom Tor support for `CFStream`? After reading your comments on the thread linked above, it seems like on the iOS side `Tor.framework` is only useful when `NSURLSession` can be used but it would not work for gRPC (Sockets).

I had a [similar conversation](https://github.com/ZcashFoundation/zebra/issues/1019) and was pointed toward `Tor.Framework` which seems insufficient for our iOS needs.

I ask these questions because I'm starting to think that collaborating on some stand-alone libraries for Kotlin/Swift might make sense in order to make it easier to add Tor support to mobile apps running gRPC.
