### ISSUE TITLE
Crashes from production

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#2653]
- CoreAutoLayout: _AssertAutoLayoutOnAllowedThreadsOnly
- CFNetwork: SocketStream::write(__CFWriteStream*, unsigned char const*, long, CFStreamError*) 
- Unstoppable: @objc SectionsTableView.tableView(_:trailingSwipeActionsConfigurationForRowAt:)
- Unstoppable: closure #1 in PeerConnection.connect() 
- partial apply for thunk for @callee_guaranteed (@guaranteed Database) -> (@owned PeerAddress?, @error @owned Error) 
- UIKitCore: __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 552

**Comment by ealymbaev** [comment]
- the most reported crash is fixed in #2770
- `SectionsTableView` crash is quite strange, but I have added additional check for `section` and `row` existance before refering them
- crashes related to `PeerConnection` are related to OS Streams and will be replaced with Native WebSocket in next version
