### ISSUE TITLE
Zcash blockchain sync starts from scratch after reaching 50%

### ISSUE THREAD

**Issue by rex4539** [horizontalsystems/unstoppable-wallet-ios#4006]
0.24.1

Steps:
1. Add a Zcash wallet.
2. Let it sync.

What happened:
When sync reaches 50% it goes back to 0% and starts syncing from scratch.

Expected result:
Wallet syncs till 100%

**Comment by ant013** [comment]
ZCash synchronization includes 3 steps. 

1 step - downloading sapling data required for [ZcashLightClientKit](https://github.com/zcash/ZcashLightClientKit) library which we using.
because our UI support only the 'syncing' state for all blockchains, we show 'syncing...' from 0 to 100% while downloading sapling

2 step - ZcashLightClientKit starts download blocks (syncing from 0 to 50%). Every time when you close or minimize the app and then open again, the library starts from the last downloaded block but returns progress again from 0% to 50%. 
(For example, you need to download 1_000_000 blocks. It starts from 0% and shows 1% when downloading the first 10_000 blocks.
if you minimize the app when it downloads 10_000 blocks, and then open again (the library will be started again)  it shows 0% syncing, but start download from 10_001 block.)

For now, 1% blocks download on WiFi can take about 1 minute(if you do not set birthday height). Your app must stay open because in the background iOS stop all downloads after about 30 seconds.

3 step - ZCashLingClientKit starts enhancing block. The same situation that in 2 steps but from 50% to 100%, and it's fastly

That's why if you restore your wallet with birthdayHeight about 1_500_000 - you will see all steps very fast. (but not right for older wallets)

**Comment by rex4539** [comment]
I have a setting when my phone never goes to sleep and is always on.

I left it syncing for about 15 minutes and it went to 50% and then back to 0% about 6 times.

How much time I need to leave it sync? An hour or so?

**Comment by ant013** [comment]
Potentially it can be if sapling data not downloads correctly. Then it tries to download again sapling. But i can't reproduce that.
If you saw first step from 0 to 100% and then every time from 0-50% and again : it's problem with downloading blocks (Maybe turn off token, and restore it again can help)
If you don't saw first step, (wallet doesn't download sapling) you can try restore again but using another network (Wifi or other lte)

**Comment by ealymbaev** [comment]
@rex4539, developer @ant013 has refactored sync progress reporting for Zcash in #4010. Thus now you should see only one unified progress for all sync steps.
